### ISSUE TITLE
Not all expected packages marked for deletion

### ISSUE THREAD

**Issue by MathMagique** [blue-yonder/devpi-cleaner#2]
devpi-cleaner does not remove all packages. With a command such as

```
devpi-cleaner server user 'package<1.0' --dev-only
```

Some packages remain on the server:

```
package-0.11-py2-none-any.whl            *
package-0.11c1-py2-none-any.whl          *
package-0.10.1-py2-none-any.whl          *
package-0.10.post47-py2-none-any.whl
package-0.10.post46-py2-none-any.whl
package-0.10.post44-py2-none-any.whl
package-0.10.post4-py2-none-any.whl
package-0.10-py2-none-any.whl            *
package-0.10c2-py2-none-any.whl          *
package-0.10c1-py2-none-any.whl          *
package-0.9.post66-py2-none-any.whl
package-0.9.post61-py2-none-any.whl
package-0.9.post60-py2-none-any.whl
package-0.9.post59-py2-none-any.whl
package-0.9.post57-py2-none-any.whl
package-0.9.post56-py2-none-any.whl
package-0.9.post49-py2-none-any.whl
package-0.9.post47-py2-none-any.whl
package-0.9.post37-py2-none-any.whl
package-0.9.post36-py2-none-any.whl
package-0.9.post35-py2-none-any.whl
package-0.9.post33-py2-none-any.whl
```

I would expect packages marked with an asterisk to stay.
Additional context: There is no stable 0.9 version on the server. Maybe there is some confusion with single-digit versions?

**Comment by ghost** [comment]
The issue is that according Léon categorizes the packages according to [PEP 440](https://www.python.org/dev/peps/pep-0440). According to that [development releases contain `.dev` in their version](https://www.python.org/dev/peps/pep-0440/#developmental-releases), which Léon uses for their detection.
The packages that you would expect to be deleted are technically [post releases](https://www.python.org/dev/peps/pep-0440/#post-releases), and to my knowledge would also be selected by PIP without using the `--pre` flag. So these _are_ stable releases according to the semantics of PEP 330 and they can not in general be removed safely.
As it seems some automatic versioning tools generate such post-release versions for untagged builds I see a use case for automatic removal. However, I fear it would probably be better contained in an additional selector (e.g. `--post`) instead of broadening the definition of a development package to something not matching PEP 440 and thus possible surprising the user in a dangerous way.
